env:
  REVISION: "$BUILDKITE_COMMIT"
  ECR_URL: "765337109446.dkr.ecr.us-east-1.amazonaws.com/registry-client"

steps:
  - name: ":docker: build django_super_deduper"
    agents:
      queue: new-builders  #FIXME
    plugins:
      docker-compose#v3.0.2:
        build: django-super-deduper
        config:
          - docker-compose.yml
        image-repository: "$BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY"

  - wait

  - name: "pytest"
    command:
      # - pytest --cov=./django_super_deduper
      - pytest
    agents:
      queue: new-pytest  #FIXME
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml
          # - docker-compose.ci.yml

  - name: "mypy"
    command: mypy django_super_deduper/
    agents:
      queue: new-default  #FIXME
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
            - docker-compose.yml

  - name: "isort"
    command: isort --check-only
    agents:
      queue: new-default  #FIXME
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml

  - name: "flake8"
    command: flake8
    agents:
      queue: new-default  #FIXME
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml
