env:
  REVISION: "$BUILDKITE_COMMIT"

steps:
  - name: ":docker: build django_super_deduper"
    agents:
      queue: builders
    plugins:
      docker-compose#v3.0.2:
        build: django-super-deduper
        config:
          - docker-compose.yml
        image-repository: "$BUILDKITE_PLUGIN_DOCKER_COMPOSE_IMAGE_REPOSITORY"

  - wait

  - name: "pytest"
    command:
      - pytest
    agents:
      queue: pytest
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml

  - name: "mypy"
    command: mypy django_super_deduper/
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
            - docker-compose.yml

  - name: "isort"
    command: isort --check-only
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml

  - name: "flake8"
    command: flake8
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.2:
        run: django-super-deduper
        config:
          - docker-compose.yml
